//
//  QSBookCommentProtocols.swift
//  zhuishushenqi
//
//  Created caonongyun on 2017/4/24.
//  Copyright © 2017年 QS. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol QSBookCommentWireframeProtocol: class {

}
//MARK: Presenter -
protocol QSBookCommentPresenterProtocol: class {
    func viewDidLoad()
    func requestMore()
}

//MARK: Interactor -
protocol QSBookCommentInteractorProtocol: class {
    func requestHot()
    func requestNormal()
    func requestDetail()
}

//MARK: Output - 
protocol QSBookCommentInteractorOutputProtocol: class {
    func fetchDetailSuccess(detail:BookComment)
    func fetchDetailFailed()
    func fetchHotSuccess(hots:[BookCommentDetail])
    func fetchHotFailed()
    func fetchNormalSuccess(normals:[BookCommentDetail])
    func fetchNormalFailed()
}

//MARK: View -
protocol QSBookCommentViewProtocol: IndicatableView {

  var presenter: QSBookCommentPresenterProtocol?  { get set }
    
    func showDetail(detail:BookComment)
    func showHot(hots:[BookCommentDetail])
    func showNormal(normals:[BookCommentDetail])
    func showEmpty()
}
