//
//  QSCategoryDetailProtocols.swift
//  zhuishushenqi
//
//  Created caonongyun on 2017/4/20.
//  Copyright © 2017年 QS. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol QSCategoryDetailWireframeProtocol: class {
    func presentDetail(book:Book)
}
//MARK: Presenter -
protocol QSCategoryDetailPresenterProtocol: class {
    func viewDidLoad()
    func didSelectAt(index:Int)
    func didSelectRowAt(indexPath:IndexPath)
}

//MARK: Interactor -
protocol QSCategoryDetailInteractorProtocol: class {
    func request(index:Int)
    func showSeg()
    func showDetail(indexPath:IndexPath)
}

//MARK: Output - 
protocol QSCategoryDetailInteractorOutputProtocol: class {
    func fetchDataSuccess(models:[Book])
    func fetchDataFailed()
    func showSeg(titles:[String])
    func showDetail(book:Book)
}

//MARK: View -
protocol QSCategoryDetailViewProtocol: IndicatableView {

  var presenter: QSCategoryDetailPresenterProtocol?  { get set }
    func showData(books:[Book])
    func showSeg(titles:[String])
}
