//
//  QSCategoryDetailInteractor.swift
//  zhuishushenqi
//
//  Created caonongyun on 2017/4/20.
//  Copyright © 2017年 QS. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit
import QSNetwork

//        http://api.zhuishushenqi.com/book/by-categories?gender=male&type=new&major=都市&minor=&start=0&limit=50
class QSCategoryDetailInteractor: QSCategoryDetailInteractorProtocol {

    var output: QSCategoryDetailInteractorOutputProtocol?
    
    var param:[String:Any] = [:]
    
    
    func setupSegview()->[UIViewController]{
        var subviews:[UIViewController] = []
        for index in 0..<4 {
            let newBookVC = QSSegmentRouter.createModule(index: index,param: self.param)
            subviews.append(newBookVC)
        }
        return subviews
    }
}

