//
//  QSSegmentRouter.swift
//  zhuishushenqi
//
//  Created caonongyun on 2017/4/20.
//  Copyright © 2017年 QS. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class QSSegmentRouter: QSSegmentWireframeProtocol {
    
    weak var viewController: UIViewController?
    
    static func createModule(index:Int,param:[String:Any]) -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = QSSegmentViewController(nibName: nil, bundle: nil)
        let interactor = QSSegmentInteractor()
        let router = QSSegmentRouter()
        let presenter = QSSegmentPresenter(interface: view, interactor: interactor, router: router)
        
        view.presenter = presenter
        interactor.output = presenter
        router.viewController = view
        
        view.cellClass = TopDetailCell.self
        view.rowHeight = 93
        view.selectedIndex = index
        interactor.param = param

        return view
    }
    
    func presentDetail(book:Book) {
        viewController?.navigationController?.pushViewController(QSBookDetailRouter.createModule(id: book._id ?? ""), animated: true)
    }
}
