//
//  QSThemeTopicProtocols.swift
//  zhuishushenqi
//
//  Created Nory Cao on 2017/4/13.
//  Copyright © 2017年 QS. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol QSThemeTopicWireframeProtocol: class {
    func presentDetail(indexPath:IndexPath,models:[ThemeTopicModel])
}
//MARK: Presenter -
protocol QSThemeTopicPresenterProtocol: class {
    func viewDidLoad(index:Int)
    func didSelectTitle(index:Int,tag:String,gender:String)
    func didSelectSeg(index: Int)
    func didClickFilter(index:Int,title:String,name:String)
    func didSelectAt(indexPath:IndexPath,models:[ThemeTopicModel])
}
//MARK: Interactor -
protocol QSThemeTopicInteractorProtocol: class {
    func initTitle(index:Int)
    func setupSeg(index:Int)
    func filter(index:Int,title:String,name:String)
    func requestTitle(index:Int,tag:String,gender:String)
    func requestDetail(index:Int)
}

//MARK: Output -
protocol QSThemeTopicInteractorOutputProtocol: class {
    func showFilter(title:String,index: Int, tag: String, gender: String)
    func showSegView(titles:[String])
    func fetchModelSuccess(models:[ThemeTopicModel])
    func fetchModelFailed()
}


//MARK: View -
protocol QSThemeTopicViewProtocol: IndicatableView {
    var presenter: QSThemeTopicPresenterProtocol?  { get set }
    func showSeg(titles:[String])
    func showThemeTopic(models:[ThemeTopicModel])
    func showTitle(title:String,index: Int, tag: String, gender: String)
}
