//
//  QSBookDetailProtocols.swift
//  zhuishushenqi
//
//  Created caonongyun on 2017/4/13.
//  Copyright © 2017年 QS. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol QSBookDetailWireframeProtocol: class {
    func presentReading(model:[ResourceModel],booDetail:BookDetail)
    func presentComment(id:String)
}
//MARK: Presenter -
protocol QSBookDetailPresenterProtocol: class {
    func viewDidLoad(id:String)
    func didClickReadingBtn(model:BookDetail,select:Bool)
    func didClickPersueBtn(model:BookDetail,select:Bool)
    func didClickCacheAll()
    func didSelectRow(indexPath:IndexPath)
}

//MARK: Interactor -
protocol QSBookDetailInteractorProtocol: class {
    func requestData(id:String)
    func requestAllChapters(withUrl url:String,param:[String:Any])
}

//MARK: Output -
protocol QSBookDetailInteractorOutputProtocol: class {
    func fetchBookSuccess(bookDetail:BookDetail,ranks:[QSHotComment])
    func fetchRankFailed()
    func fetchContent(show:Bool)
    func fetchAllChapterSuccess(bookDetail:BookDetail,res:[ResourceModel])
    func fetchAllChapterFailed()
}


//MARK: View -
protocol QSBookDetailViewProtocol: IndicatableView {

  var presenter: QSBookDetailPresenterProtocol?  { get set }
    func showContent(show:Bool)
    func showResult(bookDetail:BookDetail,comment:[QSHotComment])
}
