//
//  QSCatalogProtocols.swift
//  zhuishushenqi
//
//  Created caonongyun on 2017/4/21.
//  Copyright © 2017年 QS. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation
import UIKit

//MARK: Wireframe -
protocol QSCatalogWireframeProtocol: class {
    func presentDetail(param:[String:Any])
}
//MARK: Presenter -
protocol QSCatalogPresenterProtocol: class {
    func viewDidLoad()
    func didSelectAt(index:Int,indexPath:IndexPath)
}

//MARK: Interactor -
protocol QSCatalogInteractorProtocol: class {
    func requestDetail()
    func show(index:Int,indexPath:IndexPath)
}

//MARK: Output - 
protocol QSCatalogInteractorOutputProtocol: class {
    func fetchDataSuccess(models:[[NSDictionary]])
    func fetchDataFailed()
    func showDetail(param:[String:Any])
}

//MARK: View -
protocol QSCatalogViewProtocol: IndicatableView {

  var presenter: QSCatalogPresenterProtocol?  { get set }
    func showData(models:[[NSDictionary]])
}
