//
//  QSCatalogRouter.swift
//  zhuishushenqi
//
//  Created caonongyun on 2017/4/21.
//  Copyright © 2017年 QS. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class QSCatalogRouter: QSCatalogWireframeProtocol {
    
    weak var viewController: UIViewController?
    
    static func createModule() -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = QSCatalogViewController(nibName: nil, bundle: nil)
        let interactor = QSCatalogInteractor()
        let router = QSCatalogRouter()
        let presenter = QSCatalogPresenter(interface: view, interactor: interactor, router: router)
        
        view.presenter = presenter
        interactor.output = presenter
        router.viewController = view
        
        return view
    }
    
    func presentDetail(param:[String:Any]){
        viewController?.navigationController?.pushViewController(QSCategoryDetailRouter.createModule(param: param), animated: true)
    }
}
