//
//  QSBookCommentRouter.swift
//  zhuishushenqi
//
//  Created yung on 2017/4/24.
//  Copyright © 2017年 QS. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class QSBookCommentRouter: QSBookCommentWireframeProtocol {
    
    weak var viewController: UIViewController?
    
    static func createModule(model:BookComment) -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = QSBookCommentViewController(nibName: nil, bundle: nil)
        let interactor = QSBookCommentInteractor()
        let router = QSBookCommentRouter()
        let presenter = QSBookCommentPresenter(interface: view, interactor: interactor, router: router)
        
        view.presenter = presenter
        interactor.output = presenter
        router.viewController = view
        
        interactor.model = model
        
        return view
    }
}
