//
//  QSTopicDetailProtocols.swift
//  zhuishushenqi
//
//  Created caonongyun on 2017/4/20.
//  Copyright © 2017年 QS. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol QSTopicDetailWireframeProtocol: class {
    func presentDetail(indexPath:IndexPath,models:[TopicDetailModel])
}
//MARK: Presenter -
protocol QSTopicDetailPresenterProtocol: class {
    func viewDidLoad()
    func didSelectAt(indexPath:IndexPath,models:[TopicDetailModel])
}

//MARK: Interactor -
protocol QSTopicDetailInteractorProtocol: class {
    func requestDetail()
    func showTitle()
}

//MARK: Output - 
protocol QSTopicDetailInteractorOutputProtocol: class {
    func fetchListSuccess(list:[TopicDetailModel],header:TopicDetailHeader)
    func fetchListFailed()
    func showTitle(title:String)
}

//MARK: View -
protocol QSTopicDetailViewProtocol: IndicatableView {

  var presenter: QSTopicDetailPresenterProtocol?  { get set }
    func showList(list:[TopicDetailModel],header:TopicDetailHeader)
    func showEmpty()
    func showTitle(title:String)
}
