//
//  QSCategoryProtocols.swift
//  zhuishushenqi
//
//  Created caonongyun on 2017/4/13.
//  Copyright © 2017年 QS. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol QSCategoryWireframeProtocol: class {
    func presentReading(model:[ResourceModel],booDetail:BookDetail)
}
//MARK: Presenter -
protocol QSCategoryPresenterProtocol: class {
    func viewDidLoad(id:String)
}

//MARK: Interactor -
protocol QSCategoryInteractorProtocol: class {

}

//MARK: Output -
protocol QSCategoryInteractorOutputProtocol: class {
  
}


//MARK: View -
protocol QSCategoryViewProtocol: IndicatableView {

  var presenter: QSCategoryPresenterProtocol?  { get set }

}
