//
//  QSCategoryInteractor.swift
//  zhuishushenqi
//
//  Created Nory Cao on 2017/4/13.
//  Copyright © 2017年 QS. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class QSCategoryInteractor: QSCategoryInteractorProtocol {

    var output: QSCategoryInteractorOutputProtocol!
    var bookDetail:BookDetail!
    
    func show(){
        if let chapters = bookDetail.chapters {
            var titles:[String] = []
            for item in chapters {
                if let title = item["title"] as? String {
                    titles.append(title)
                }
            }
            self.output.show(titles: titles)
        }
    }
    
    func showDetail() {
        self.output.showDetail(book: bookDetail)
    }
}
