//
//  QSCategoryInteractor.swift
//  zhuishushenqi
//
//  Created Nory Cao on 2017/4/13.
//  Copyright © 2017年 QS. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit
import QSNetwork

class QSCategoryInteractor: QSCategoryInteractorProtocol {

    var output: QSCategoryInteractorOutputProtocol!
    
    var bookDetail:BookDetail!
    var hotComment:[QSHotComment] = []
    
    

}
