//
//  QSCommunityPresenter.swift
//  zhuishushenqi
//
//  Created yung on 2017/4/24.
//  Copyright © 2017年 QS. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class QSCommunityPresenter: QSCommunityPresenterProtocol {

    weak var view: QSCommunityViewProtocol?
    let interactor: QSCommunityInteractorProtocol
    let router: QSCommunityWireframeProtocol

    init(interface: QSCommunityViewProtocol, interactor: QSCommunityInteractorProtocol, router: QSCommunityWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }
    
    func viewDidLoad() {
        interactor.showTitle()
        interactor.requestPost()
        view?.showActivityView()
    }
    
    func refreshData(){
        view?.showActivityView()
        interactor.requestPost()
    }
    
    func requestMore(){
        view?.showActivityView()
        interactor.requestPostMore()
    }
    
    func refreshComments(){
        view?.showActivityView()
        interactor.requestBaseComments()
    }
    
    func requestMoreComments(){
        view?.showActivityView()
        interactor.requestMoreComments()
    }
    
    func didSelectCell(indexPath: IndexPath) {
        interactor.showDetail(indexPath: indexPath)
    }
}

extension QSCommunityPresenter:QSCommunityInteractorOutputProtocol {
    func fetchPostsSuccess(posts: [BookComment]) {
        view?.hideActivityView()
        view?.showPosts(posts: posts)
    }
    
    func fetchPostsFailed() {
        view?.hideActivityView()
        view?.showEmpty()
    }
    
    func fetchCommentsSuccess(comments: [BookComment]) {
        view?.hideActivityView()
        view?.showComments(comments: comments)
    }
    
    func fetchCommentsFailed() {
        view?.hideActivityView()
        view?.showEmpty()
    }
    
    func showTitle(title: String) {
        view?.showTitle(title: title)
    }
    
    func showDetail(detail:BookComment){
        router.presentDetail(detail: detail)
    }
}
