//
//  QSCommunityProtocols.swift
//  zhuishushenqi
//
//  Created yung on 2017/4/24.
//  Copyright © 2017年 QS. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol QSCommunityWireframeProtocol: class {
    func presentDetail(detail:BookComment)
}
//MARK: Presenter -
protocol QSCommunityPresenterProtocol: class {
    func viewDidLoad()
    func refreshData()
    func requestMore()
    func refreshComments()
    func requestMoreComments()
    func didSelectCell(indexPath:IndexPath)
}

//MARK: Interactor -
protocol QSCommunityInteractorProtocol: class {
    func request()
    func requestPost()
    func requestPostMore()
    func requestComments()
    func requestBaseComments()
    func requestMoreComments()
    func showTitle()
    func showDetail(indexPath:IndexPath)
}

//MARK: Output - 
protocol QSCommunityInteractorOutputProtocol: class {
    func fetchPostsSuccess(posts:[BookComment])
    func fetchPostsFailed()
    func fetchCommentsSuccess(comments:[BookComment])
    func fetchCommentsFailed()
    func showTitle(title:String)
    func showDetail(detail:BookComment)
}

//MARK: View -
protocol QSCommunityViewProtocol: IndicatableView {

  var presenter: QSCommunityPresenterProtocol?  { get set }
    func showPosts(posts:[BookComment])
    func showEmpty()
    func showComments(comments:[BookComment])
    func showTitle(title:String)
}
