//
//  QSCatalogProtocols.swift
//  zhuishushenqi
//
//  Created yung on 2017/4/21.
//  Copyright © 2017年 QS. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//
class ZSVoiceCategoryCell: UITableViewCell {
    override init(style: UITableViewCell.CellStyle, reuseIdentifier: String?) {
        super.init(style: .value1, reuseIdentifier: reuseIdentifier)
        setupSubviews()
    }
    
    required init?(coder aDecoder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }
    
    override func layoutSubviews() {
        super.layoutSubviews()
        imageView?.frame = CGRect(x: 20, y: 10, width: bounds.height*2/3, height: bounds.height - 20)
        textLabel?.frame = CGRect(x: (imageView?.frame.maxX ?? 0) + 20, y: 10, width: bounds.width - (imageView?.frame.maxX ?? 0) - 20 - 20, height: 20)
        detailTextLabel?.frame = CGRect(x: (imageView?.frame.maxX ?? 0) + 20, y: (bounds.height - 20)/3 + 10, width: bounds.width - (imageView?.frame.maxX ?? 0) - 20 - 20, height: 20)
        popularityLabel.frame = CGRect(x: (imageView?.frame.maxX ?? 0) + 20, y: (bounds.height - 20)*2/3 + 10, width: (bounds.width - (imageView?.frame.maxX ?? 0))/2 - 20, height: 20)
        
        totalLabel.frame = CGRect(x: (popularityLabel?.frame.midX ?? 0) + 40 , y: (bounds.height - 20)*2/3 + 10, width: (bounds.width - (imageView?.frame.maxX ?? 0))/2 + 20, height: 20)
    }
    
    private func setupSubviews() {
        textLabel?.font = UIFont.systemFont(ofSize: 15)
        detailTextLabel?.font = UIFont.systemFont(ofSize: 13)
        
        popularityLabel = UILabel()
        popularityLabel.font = UIFont.systemFont(ofSize: 12)
        popularityLabel.textColor = UIColor.gray
        contentView.addSubview(popularityLabel)
        
        totalLabel = UILabel()
        totalLabel.font = UIFont.systemFont(ofSize: 12)
        totalLabel.textColor = UIColor.gray
        contentView.addSubview(totalLabel)
    }
    
    var popularityLabel:UILabel!
    var totalLabel:UILabel!
}
