//
//  QSCommunityInteractor.swift
//  zhuishushenqi
//
//  Created caonongyun on 2017/4/24.
//  Copyright © 2017年 QS. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit
import QSNetwork

class QSCommunityInteractor: QSCommunityInteractorProtocol {

    var output: QSCommunityInteractorOutputProtocol?
    
    var model:BookDetail!
    var posts:[BookComment] = []
    var comments:[BookComment] = []
    
    var postStart:Int = 0
    var commentStart:Int = 0
    var selectedIndex = 0
    
    func requestPost(){
        selectedIndex = 0
        postStart = 0
        request()
    }
    
    func request(){
//        http://api.zhuishushenqi.com/post/by-book?book=51d11e782de6405c45000068&sort=updated&type=normal,vote&start=0&limit=20
        let url = "\(BASEURL)/post/by-book?book=\(model._id)&sort=updated&type=normal,vote&start=\(postStart)&limit=20"
        QSNetwork.request(url) { (response) in
            if let json = response.json?["posts"] as? NSArray {
                do{
                    let posts = try XYCBaseModel.model(withModleClass: BookComment.self, withJsArray: json as! [Any]) as? [BookComment]
                    if let models = posts {
                        if self.postStart == 0{
                            self.posts = models
                        }else{
                            self.posts.append(contentsOf: models)
                        }
                        self.output?.fetchPostsSuccess(posts: self.posts)
                    }else {
                        self.output?.fetchPostsFailed()
                    }
                } catch {
                    self.output?.fetchPostsFailed()
                }
            }else {
                self.output?.fetchPostsFailed()
            }
        }
    }
    
    func requestPostMore(){
        selectedIndex = 0
        postStart += 20
        request()
    }
    
    func requestBaseComments(){
        selectedIndex = 1
        commentStart = 0
        requestComments()
    }
    
    func requestMoreComments(){
        selectedIndex = 1
        commentStart += 20
        requestComments()
    }
    
    func requestComments(){
//        http://api.zhuishushenqi.com/post/review/by-book?book=51d11e782de6405c45000068&sort=updated&start=0&limit=20
        let url = "\(BASEURL)/post/review/by-book?book=\(model._id)&sort=updated&start=\(commentStart)&limit=20"
        QSNetwork.request(url) { (response) in
            if let json = response.json?["reviews"] as? NSArray {
                do{
                    let posts = try XYCBaseModel.model(withModleClass: BookComment.self, withJsArray: json as! [Any]) as? [BookComment]
                    if let models = posts {
                        if self.commentStart == 0{
                            self.comments = models
                        }else{
                            self.comments.append(contentsOf: models)
                        }
                        self.output?.fetchCommentsSuccess(comments: self.comments)
                    }else {
                        self.output?.fetchCommentsFailed()
                    }
                } catch {
                    self.output?.fetchCommentsFailed()
                }
            }else {
                self.output?.fetchCommentsFailed()
            }
        }
    }
    
    
    func showTitle(){
        self.output?.showTitle(title: model.title)
    }
    
    func showDetail(indexPath: IndexPath) {
        if selectedIndex == 0 {
            self.output?.showDetail(detail: posts[indexPath.row])
        }else{
            self.output?.showDetail(detail: comments[indexPath.row])
        }
    }
}
