//
//  QSCatalogInteractor.swift
//  zhuishushenqi
//
//  Created yung on 2017/4/21.
//  Copyright © 2017年 QS. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//
class ZSThemeTopicViewModel {
    
    var sort:String = ""
    var duration:String = ""
    
    func request() {
        
    }
}
