//
//  QSCategoryProtocols.swift
//  zhuishushenqi
//
//  Created Nory Cao on 2017/4/13.
//  Copyright © 2017年 QS. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol QSCategoryWireframeProtocol: class {
    func presentReading(model:[ResourceModel],booDetail:BookDetail)
}
//MARK: Presenter -
protocol QSCategoryPresenterProtocol: class {
    func viewDidLoad()
}

//MARK: Interactor -
protocol QSCategoryInteractorProtocol: class {
    func show()
    func showDetail()
}

//MARK: Output -
protocol QSCategoryInteractorOutputProtocol: class {
    func show(titles:[String])
    func showDetail(book:BookDetail)
}


//MARK: View -
protocol QSCategoryViewProtocol: IndicatableView {

  var presenter: QSCategoryPresenterProtocol?  { get set }
    func show(titles:[String])
    func showDetail(book:BookDetail)
}
